DROP TABLE IF EXISTS user;

DROP TABLE IF EXISTS pet;

DROP TABLE IF EXISTS user_pet;

DROP TABLE IF EXISTS meal;

CREATE TABLE
  user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
  );

CREATE TABLE
  pet (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    birthday TIMESTAMP NOT NULL,
    weight REAL NOT NULL,
    species TEXT NOT NULL,
    photo BLOB,
    user_id INTEGER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES user (id)
  );

CREATE TABLE
  user_pet (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    pet_id INTEGER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE,
    FOREIGN KEY (pet_id) REFERENCES pet (id) ON DELETE CASCADE
  );

CREATE TABLE
  meal (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    pet_id INTEGER NOT NULL,
    quantity INTEGER NOT NULL,
    datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE,
    FOREIGN KEY (pet_id) REFERENCES pet (id) ON DELETE CASCADE
  );

CREATE TRIGGER after_pet_insert AFTER INSERT ON pet FOR EACH ROW BEGIN
INSERT INTO
  user_pet (pet_id, user_id)
VALUES
  (NEW.id, NEW.user_id);

END;

PRAGMA foreign_keys = ON;